alias reloadcli="source $HOME/.bashrc"
alias c="clear"
alias l="ls -ahlF --color=auto"
alias pubkey="cat $HOME/.ssh/id_rsa.pub"
alias weather="curl -4 http://wttr.in"
alias togit="cd $HOME/git"
alias glog="git log --graph --pretty=format:'%Cred%h%Creset %an: %s - %Creset %C(yellow)%d%Creset %Cgreen(%cr)%Creset' --abbrev-commit --date=relative"
alias wanip="dig -4 TXT +short o-o.myaddr.l.google.com @ns1.google.com | sed 's/\"//g'"
alias pws="keepassxc ~/Documents/database.kdbx &"
alias sc="import png:- | xclip -selection clipboard -t image/png"
